function [] = mtitle(string, dz, varargin)


annotation('textbox',[0, 1-dz, 1, dz], 'String', string, ...
    'FitBoxToText','off', 'horizontalalignment', 'center', ...
    'verticalalignment', 'bottom',...
    'fontweight', 'bold', 'linestyle', 'none', varargin{:});